### ISSUE TITLE
How to train the model with my data from scratch?

### ISSUE THREAD

**Issue by cbqin** [PolyAI-LDN/polyai-models#23]
Hi, it seems there is no training and model code in the repository. I want to train another model in other languages, what should I do? Thanks!

**Comment by matthen** [comment]
That's right, we are not providing the pretraining code at this point, just the pretrained models. You can try finetuning the models to your own data, or extracting relevant bits out of the tensorflow graph in constructing a model (with a subword different vocabulary presumably)
