### ISSUE TITLE
TF Hub modules not compatible with TensorFlow 2.0

### ISSUE THREAD

**Issue by karlhayek** [PolyAI-LDN/polyai-models#30]
Hello, thanks for sharing this repo. The README mentions that the ConveRT models are compatible with TF 2.0, but loading their tfhub modules while using TF 2.0 yields an error. Do you plan on updating the modules and example notebook to be compatible with Tensorflow 2.0?

**Comment by matthen** [comment]
please can you share the error, and the code you are using?

**Comment by karlhayek** [comment]
Sure, running on Colab after installing tensorflow_text:

<img width="770" alt="Screen Shot 2020-01-17 at 2 58 10 PM" src="https://user-images.githubusercontent.com/26654394/72614037-e53b2880-3939-11ea-89e4-74a2adddb3c1.png">

Disabling eager execution with `tf.compat.v1.disable_eager_execution()` fixes the issue but this means the modules aren't compatible with TF 2.0 out of the box since eager execution is enabled by default.

**Comment by matthen** [comment]
Thanks! I will add a todo to export a version that works with eager execution, and in the meantime add a note that t needs to be disabled in tf 2.0.
